# Generated by Django 5.0.2 on 2024-02-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_alter_user_is_admin_alter_user_is_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
