# Generated by Django 5.0.2 on 2024-02-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
