# Generated by Django 5.0.2 on 2024-02-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='caption',
        ),
    ]
