# Generated by Django 5.0.2 on 2024-02-10 20:14

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth_app', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True, verbose_name='カテゴリーのid')),
                ('title', models.CharField(default='Food', max_length=100, verbose_name='カテゴリー名')),
                ('image', models.ImageField(default='category.jpg', upload_to='category', verbose_name='カテゴリーの写真')),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Cloth_app.category', verbose_name='カテゴリー'),
        ),
    ]
